on:
  push:
    branches:
      - master
name: Publish Website
jobs:
  build_css:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout source Git branch
          uses: actions/checkout@v2
          with:
              ref: master
              fetch-depth: 10
              submodules: true

        - name: Make destination directory for compiled CSS
          run: mkdir -vp /tmp/repo-name/assets/css

        - name: Compile CSS from SCSS files
          uses: gha-utilities/sass-build@v0.2.2
          with:
            source: assets/sass/main.scss
            destination: /tmp/repo-name/assets/css/main.css

        - name: Checkout destination Git branch
          uses: actions/checkout@v2
          with:
              ref: master
              fetch-depth: 1

        - name: Move compiled CSS to path within master branch
          run: mv /tmp/repo-name/assets/css assets/

        - name: Add and Commit changes to pr-pages branch
          run:
            git config --local user.email 'action@github.com'
            git config --local user.name 'GitHub Action'
            git add assets/css/*
            git commit -m 'Updates compiled CSS files'

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.TOKEN }}
            branch: master

  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.calgallisa.com/web/
        ftp-username: calgalli
        ftp-password: ${{ secrets.FTP_PASSWORD }}
